// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/google/uuid"
)

type Message struct {
	ID      uuid.UUID
	Content string
	Status  string
}
